server:
  port: 10301
  
###################  服务配置  ###################
bdtd:
  multiple-db: false
  file-upload-path: d:/bdtd/upload
  spring-session-open: false #是否开启spring session,如果是多机环境需要开启(true/false)
  session-invalidate-time: 1800 #session失效时间(只在单机环境下生效，多机环境在SpringSessionConfig类中配置) 单位：秒
  session-validation-interval: 900 #多久检测一次失效的session(只在单机环境下生效) 单位：秒
  
###################  spring配置  ###################
spring:
  profiles:
    active: dev
  devtools:
    restart:
      enabled: true #是否开启开发者工具（true/false）
      additional-paths: src/main/java
      exclude: static/**,WEB-INF/view/**
  aop:
    proxy-target-class: true #false为启用jdk默认动态代理,true为cglib动态代理
    

###################  mybatis-plus配置  ###################
mybatis-plus:
  mapper-locations: classpath*:mybatis/*/*Mapper.xml
  typeAliasesPackage: com.bdtd.card.data.*.model
  global-config:
    id-type: 0  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
    logic-delete-value: 0
    logic-not-delete-value: 1
  configuration:
    map-underscore-to-camel-case: false
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
  
---    
##########################################################
###################  开发环境的profile  ###################
##########################################################
spring:
  profiles: dev
  datasource:
   username: root
   password: root
   url:  jdbc:mysql://127.0.0.1:3306/bdtd_card?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
   driver-class-name: com.mysql.jdbc.Driver
   filters: wall,mergeStat
   
logging:
  level.root: info
  level.com.bdtd.card: debug
#  level.com.stylefeng.guns.modular.system.dao: debug
#  level.com.stylefeng.guns.core.aop.FileLogAop: debug
  path: logs/
  file: card.log
  
---    
##########################################################
###################  正式环境的profile  ###################
##########################################################
spring:
  profiles: prod
  datasource:
   username: root
   password: root
   url:  jdbc:mysql://127.0.0.1:3306/bdtd_card?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
   driver-class-name: com.mysql.jdbc.Driver
   filters: log4j,wall,mergeStat
   
logging:
  level.root: info
  level.com.bdtd.card: info
  path: logs/
  file: card.log