// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PBLog.proto

package com.bdtd.card.common.log.protobuf;

public final class PBLog {
  private PBLog() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PBKeyValuePairOrBuilder extends
      // @@protoc_insertion_point(interface_extends:VWVO.NetworkComponent.Globals.Command.Protobuf.PBKeyValuePair)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string key = 1;</code>
     */
    boolean hasKey();
    /**
     * <code>required string key = 1;</code>
     */
    java.lang.String getKey();
    /**
     * <code>required string key = 1;</code>
     */
    com.google.protobuf.ByteString
        getKeyBytes();

    /**
     * <code>required string value = 2;</code>
     */
    boolean hasValue();
    /**
     * <code>required string value = 2;</code>
     */
    java.lang.String getValue();
    /**
     * <code>required string value = 2;</code>
     */
    com.google.protobuf.ByteString
        getValueBytes();
  }
  /**
   * Protobuf type {@code VWVO.NetworkComponent.Globals.Command.Protobuf.PBKeyValuePair}
   */
  public  static final class PBKeyValuePair extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:VWVO.NetworkComponent.Globals.Command.Protobuf.PBKeyValuePair)
      PBKeyValuePairOrBuilder {
    // Use PBKeyValuePair.newBuilder() to construct.
    private PBKeyValuePair(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PBKeyValuePair() {
      key_ = "";
      value_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PBKeyValuePair(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              key_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              value_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bdtd.card.common.log.protobuf.PBLog.internal_static_VWVO_NetworkComponent_Globals_Command_Protobuf_PBKeyValuePair_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bdtd.card.common.log.protobuf.PBLog.internal_static_VWVO_NetworkComponent_Globals_Command_Protobuf_PBKeyValuePair_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bdtd.card.common.log.protobuf.PBLog.PBKeyValuePair.class, com.bdtd.card.common.log.protobuf.PBLog.PBKeyValuePair.Builder.class);
    }

    private int bitField0_;
    public static final int KEY_FIELD_NUMBER = 1;
    private volatile java.lang.Object key_;
    /**
     * <code>required string key = 1;</code>
     */
    public boolean hasKey() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string key = 1;</code>
     */
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          key_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string key = 1;</code>
     */
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VALUE_FIELD_NUMBER = 2;
    private volatile java.lang.Object value_;
    /**
     * <code>required string value = 2;</code>
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string value = 2;</code>
     */
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          value_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string value = 2;</code>
     */
    public com.google.protobuf.ByteString
        getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasKey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, key_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, value_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, key_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, value_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.bdtd.card.common.log.protobuf.PBLog.PBKeyValuePair)) {
        return super.equals(obj);
      }
      com.bdtd.card.common.log.protobuf.PBLog.PBKeyValuePair other = (com.bdtd.card.common.log.protobuf.PBLog.PBKeyValuePair) obj;

      boolean result = true;
      result = result && (hasKey() == other.hasKey());
      if (hasKey()) {
        result = result && getKey()
            .equals(other.getKey());
      }
      result = result && (hasValue() == other.hasValue());
      if (hasValue()) {
        result = result && getValue()
            .equals(other.getValue());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasKey()) {
        hash = (37 * hash) + KEY_FIELD_NUMBER;
        hash = (53 * hash) + getKey().hashCode();
      }
      if (hasValue()) {
        hash = (37 * hash) + VALUE_FIELD_NUMBER;
        hash = (53 * hash) + getValue().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.bdtd.card.common.log.protobuf.PBLog.PBKeyValuePair parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bdtd.card.common.log.protobuf.PBLog.PBKeyValuePair parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bdtd.card.common.log.protobuf.PBLog.PBKeyValuePair parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bdtd.card.common.log.protobuf.PBLog.PBKeyValuePair parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bdtd.card.common.log.protobuf.PBLog.PBKeyValuePair parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bdtd.card.common.log.protobuf.PBLog.PBKeyValuePair parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bdtd.card.common.log.protobuf.PBLog.PBKeyValuePair parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.bdtd.card.common.log.protobuf.PBLog.PBKeyValuePair parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bdtd.card.common.log.protobuf.PBLog.PBKeyValuePair parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bdtd.card.common.log.protobuf.PBLog.PBKeyValuePair parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.bdtd.card.common.log.protobuf.PBLog.PBKeyValuePair prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code VWVO.NetworkComponent.Globals.Command.Protobuf.PBKeyValuePair}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:VWVO.NetworkComponent.Globals.Command.Protobuf.PBKeyValuePair)
        com.bdtd.card.common.log.protobuf.PBLog.PBKeyValuePairOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.bdtd.card.common.log.protobuf.PBLog.internal_static_VWVO_NetworkComponent_Globals_Command_Protobuf_PBKeyValuePair_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.bdtd.card.common.log.protobuf.PBLog.internal_static_VWVO_NetworkComponent_Globals_Command_Protobuf_PBKeyValuePair_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.bdtd.card.common.log.protobuf.PBLog.PBKeyValuePair.class, com.bdtd.card.common.log.protobuf.PBLog.PBKeyValuePair.Builder.class);
      }

      // Construct using com.bdtd.card.base.common.log.protobuf.PBLog.PBKeyValuePair.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        key_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        value_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bdtd.card.common.log.protobuf.PBLog.internal_static_VWVO_NetworkComponent_Globals_Command_Protobuf_PBKeyValuePair_descriptor;
      }

      public com.bdtd.card.common.log.protobuf.PBLog.PBKeyValuePair getDefaultInstanceForType() {
        return com.bdtd.card.common.log.protobuf.PBLog.PBKeyValuePair.getDefaultInstance();
      }

      public com.bdtd.card.common.log.protobuf.PBLog.PBKeyValuePair build() {
        com.bdtd.card.common.log.protobuf.PBLog.PBKeyValuePair result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.bdtd.card.common.log.protobuf.PBLog.PBKeyValuePair buildPartial() {
        com.bdtd.card.common.log.protobuf.PBLog.PBKeyValuePair result = new com.bdtd.card.common.log.protobuf.PBLog.PBKeyValuePair(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.key_ = key_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.value_ = value_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bdtd.card.common.log.protobuf.PBLog.PBKeyValuePair) {
          return mergeFrom((com.bdtd.card.common.log.protobuf.PBLog.PBKeyValuePair)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.bdtd.card.common.log.protobuf.PBLog.PBKeyValuePair other) {
        if (other == com.bdtd.card.common.log.protobuf.PBLog.PBKeyValuePair.getDefaultInstance()) return this;
        if (other.hasKey()) {
          bitField0_ |= 0x00000001;
          key_ = other.key_;
          onChanged();
        }
        if (other.hasValue()) {
          bitField0_ |= 0x00000002;
          value_ = other.value_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasKey()) {
          return false;
        }
        if (!hasValue()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.bdtd.card.common.log.protobuf.PBLog.PBKeyValuePair parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.bdtd.card.common.log.protobuf.PBLog.PBKeyValuePair) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object key_ = "";
      /**
       * <code>required string key = 1;</code>
       */
      public boolean hasKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string key = 1;</code>
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            key_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string key = 1;</code>
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string key = 1;</code>
       */
      public Builder setKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        key_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string key = 1;</code>
       */
      public Builder clearKey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      /**
       * <code>required string key = 1;</code>
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        key_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object value_ = "";
      /**
       * <code>required string value = 2;</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string value = 2;</code>
       */
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            value_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string value = 2;</code>
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string value = 2;</code>
       */
      public Builder setValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string value = 2;</code>
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000002);
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      /**
       * <code>required string value = 2;</code>
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        value_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:VWVO.NetworkComponent.Globals.Command.Protobuf.PBKeyValuePair)
    }

    // @@protoc_insertion_point(class_scope:VWVO.NetworkComponent.Globals.Command.Protobuf.PBKeyValuePair)
    private static final com.bdtd.card.common.log.protobuf.PBLog.PBKeyValuePair DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.bdtd.card.common.log.protobuf.PBLog.PBKeyValuePair();
    }

    public static com.bdtd.card.common.log.protobuf.PBLog.PBKeyValuePair getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<PBKeyValuePair>
        PARSER = new com.google.protobuf.AbstractParser<PBKeyValuePair>() {
      public PBKeyValuePair parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PBKeyValuePair(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PBKeyValuePair> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PBKeyValuePair> getParserForType() {
      return PARSER;
    }

    public com.bdtd.card.common.log.protobuf.PBLog.PBKeyValuePair getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PBLogInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:VWVO.NetworkComponent.Globals.Command.Protobuf.PBLogInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required sint32 module_id = 1;</code>
     */
    boolean hasModuleId();
    /**
     * <code>required sint32 module_id = 1;</code>
     */
    int getModuleId();

    /**
     * <code>required sint32 log_type = 2;</code>
     */
    boolean hasLogType();
    /**
     * <code>required sint32 log_type = 2;</code>
     */
    int getLogType();

    /**
     * <code>required sint32 log_level = 3;</code>
     */
    boolean hasLogLevel();
    /**
     * <code>required sint32 log_level = 3;</code>
     */
    int getLogLevel();

    /**
     * <code>required string log_message = 4;</code>
     */
    boolean hasLogMessage();
    /**
     * <code>required string log_message = 4;</code>
     */
    java.lang.String getLogMessage();
    /**
     * <code>required string log_message = 4;</code>
     */
    com.google.protobuf.ByteString
        getLogMessageBytes();

    /**
     * <code>optional string exception = 5;</code>
     */
    boolean hasException();
    /**
     * <code>optional string exception = 5;</code>
     */
    java.lang.String getException();
    /**
     * <code>optional string exception = 5;</code>
     */
    com.google.protobuf.ByteString
        getExceptionBytes();

    /**
     * <code>required sint64 error_code = 6;</code>
     */
    boolean hasErrorCode();
    /**
     * <code>required sint64 error_code = 6;</code>
     */
    long getErrorCode();

    /**
     * <code>required sint64 time_stamp = 7;</code>
     */
    boolean hasTimeStamp();
    /**
     * <code>required sint64 time_stamp = 7;</code>
     */
    long getTimeStamp();

    /**
     * <code>required string default_formatted_message = 8;</code>
     */
    boolean hasDefaultFormattedMessage();
    /**
     * <code>required string default_formatted_message = 8;</code>
     */
    java.lang.String getDefaultFormattedMessage();
    /**
     * <code>required string default_formatted_message = 8;</code>
     */
    com.google.protobuf.ByteString
        getDefaultFormattedMessageBytes();

    /**
     * <code>repeated .VWVO.NetworkComponent.Globals.Command.Protobuf.PBKeyValuePair user_values = 9;</code>
     */
    java.util.List<com.bdtd.card.common.log.protobuf.PBLog.PBKeyValuePair> 
        getUserValuesList();
    /**
     * <code>repeated .VWVO.NetworkComponent.Globals.Command.Protobuf.PBKeyValuePair user_values = 9;</code>
     */
    com.bdtd.card.common.log.protobuf.PBLog.PBKeyValuePair getUserValues(int index);
    /**
     * <code>repeated .VWVO.NetworkComponent.Globals.Command.Protobuf.PBKeyValuePair user_values = 9;</code>
     */
    int getUserValuesCount();
    /**
     * <code>repeated .VWVO.NetworkComponent.Globals.Command.Protobuf.PBKeyValuePair user_values = 9;</code>
     */
    java.util.List<? extends com.bdtd.card.common.log.protobuf.PBLog.PBKeyValuePairOrBuilder> 
        getUserValuesOrBuilderList();
    /**
     * <code>repeated .VWVO.NetworkComponent.Globals.Command.Protobuf.PBKeyValuePair user_values = 9;</code>
     */
    com.bdtd.card.common.log.protobuf.PBLog.PBKeyValuePairOrBuilder getUserValuesOrBuilder(
        int index);

    /**
     * <code>required sint32 node_id = 10;</code>
     */
    boolean hasNodeId();
    /**
     * <code>required sint32 node_id = 10;</code>
     */
    int getNodeId();
  }
  /**
   * Protobuf type {@code VWVO.NetworkComponent.Globals.Command.Protobuf.PBLogInfo}
   */
  public  static final class PBLogInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:VWVO.NetworkComponent.Globals.Command.Protobuf.PBLogInfo)
      PBLogInfoOrBuilder {
    // Use PBLogInfo.newBuilder() to construct.
    private PBLogInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PBLogInfo() {
      moduleId_ = 0;
      logType_ = 0;
      logLevel_ = 0;
      logMessage_ = "";
      exception_ = "";
      errorCode_ = 0L;
      timeStamp_ = 0L;
      defaultFormattedMessage_ = "";
      userValues_ = java.util.Collections.emptyList();
      nodeId_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PBLogInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              moduleId_ = input.readSInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              logType_ = input.readSInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              logLevel_ = input.readSInt32();
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              logMessage_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              exception_ = bs;
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              errorCode_ = input.readSInt64();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              timeStamp_ = input.readSInt64();
              break;
            }
            case 66: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000080;
              defaultFormattedMessage_ = bs;
              break;
            }
            case 74: {
              if (!((mutable_bitField0_ & 0x00000100) == 0x00000100)) {
                userValues_ = new java.util.ArrayList<com.bdtd.card.common.log.protobuf.PBLog.PBKeyValuePair>();
                mutable_bitField0_ |= 0x00000100;
              }
              userValues_.add(
                  input.readMessage(com.bdtd.card.common.log.protobuf.PBLog.PBKeyValuePair.PARSER, extensionRegistry));
              break;
            }
            case 80: {
              bitField0_ |= 0x00000100;
              nodeId_ = input.readSInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000100) == 0x00000100)) {
          userValues_ = java.util.Collections.unmodifiableList(userValues_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bdtd.card.common.log.protobuf.PBLog.internal_static_VWVO_NetworkComponent_Globals_Command_Protobuf_PBLogInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bdtd.card.common.log.protobuf.PBLog.internal_static_VWVO_NetworkComponent_Globals_Command_Protobuf_PBLogInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bdtd.card.common.log.protobuf.PBLog.PBLogInfo.class, com.bdtd.card.common.log.protobuf.PBLog.PBLogInfo.Builder.class);
    }

    private int bitField0_;
    public static final int MODULE_ID_FIELD_NUMBER = 1;
    private int moduleId_;
    /**
     * <code>required sint32 module_id = 1;</code>
     */
    public boolean hasModuleId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required sint32 module_id = 1;</code>
     */
    public int getModuleId() {
      return moduleId_;
    }

    public static final int LOG_TYPE_FIELD_NUMBER = 2;
    private int logType_;
    /**
     * <code>required sint32 log_type = 2;</code>
     */
    public boolean hasLogType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required sint32 log_type = 2;</code>
     */
    public int getLogType() {
      return logType_;
    }

    public static final int LOG_LEVEL_FIELD_NUMBER = 3;
    private int logLevel_;
    /**
     * <code>required sint32 log_level = 3;</code>
     */
    public boolean hasLogLevel() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required sint32 log_level = 3;</code>
     */
    public int getLogLevel() {
      return logLevel_;
    }

    public static final int LOG_MESSAGE_FIELD_NUMBER = 4;
    private volatile java.lang.Object logMessage_;
    /**
     * <code>required string log_message = 4;</code>
     */
    public boolean hasLogMessage() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string log_message = 4;</code>
     */
    public java.lang.String getLogMessage() {
      java.lang.Object ref = logMessage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          logMessage_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string log_message = 4;</code>
     */
    public com.google.protobuf.ByteString
        getLogMessageBytes() {
      java.lang.Object ref = logMessage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        logMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXCEPTION_FIELD_NUMBER = 5;
    private volatile java.lang.Object exception_;
    /**
     * <code>optional string exception = 5;</code>
     */
    public boolean hasException() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string exception = 5;</code>
     */
    public java.lang.String getException() {
      java.lang.Object ref = exception_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          exception_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string exception = 5;</code>
     */
    public com.google.protobuf.ByteString
        getExceptionBytes() {
      java.lang.Object ref = exception_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        exception_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ERROR_CODE_FIELD_NUMBER = 6;
    private long errorCode_;
    /**
     * <code>required sint64 error_code = 6;</code>
     */
    public boolean hasErrorCode() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required sint64 error_code = 6;</code>
     */
    public long getErrorCode() {
      return errorCode_;
    }

    public static final int TIME_STAMP_FIELD_NUMBER = 7;
    private long timeStamp_;
    /**
     * <code>required sint64 time_stamp = 7;</code>
     */
    public boolean hasTimeStamp() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required sint64 time_stamp = 7;</code>
     */
    public long getTimeStamp() {
      return timeStamp_;
    }

    public static final int DEFAULT_FORMATTED_MESSAGE_FIELD_NUMBER = 8;
    private volatile java.lang.Object defaultFormattedMessage_;
    /**
     * <code>required string default_formatted_message = 8;</code>
     */
    public boolean hasDefaultFormattedMessage() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>required string default_formatted_message = 8;</code>
     */
    public java.lang.String getDefaultFormattedMessage() {
      java.lang.Object ref = defaultFormattedMessage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          defaultFormattedMessage_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string default_formatted_message = 8;</code>
     */
    public com.google.protobuf.ByteString
        getDefaultFormattedMessageBytes() {
      java.lang.Object ref = defaultFormattedMessage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        defaultFormattedMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USER_VALUES_FIELD_NUMBER = 9;
    private java.util.List<com.bdtd.card.common.log.protobuf.PBLog.PBKeyValuePair> userValues_;
    /**
     * <code>repeated .VWVO.NetworkComponent.Globals.Command.Protobuf.PBKeyValuePair user_values = 9;</code>
     */
    public java.util.List<com.bdtd.card.common.log.protobuf.PBLog.PBKeyValuePair> getUserValuesList() {
      return userValues_;
    }
    /**
     * <code>repeated .VWVO.NetworkComponent.Globals.Command.Protobuf.PBKeyValuePair user_values = 9;</code>
     */
    public java.util.List<? extends com.bdtd.card.common.log.protobuf.PBLog.PBKeyValuePairOrBuilder> 
        getUserValuesOrBuilderList() {
      return userValues_;
    }
    /**
     * <code>repeated .VWVO.NetworkComponent.Globals.Command.Protobuf.PBKeyValuePair user_values = 9;</code>
     */
    public int getUserValuesCount() {
      return userValues_.size();
    }
    /**
     * <code>repeated .VWVO.NetworkComponent.Globals.Command.Protobuf.PBKeyValuePair user_values = 9;</code>
     */
    public com.bdtd.card.common.log.protobuf.PBLog.PBKeyValuePair getUserValues(int index) {
      return userValues_.get(index);
    }
    /**
     * <code>repeated .VWVO.NetworkComponent.Globals.Command.Protobuf.PBKeyValuePair user_values = 9;</code>
     */
    public com.bdtd.card.common.log.protobuf.PBLog.PBKeyValuePairOrBuilder getUserValuesOrBuilder(
        int index) {
      return userValues_.get(index);
    }

    public static final int NODE_ID_FIELD_NUMBER = 10;
    private int nodeId_;
    /**
     * <code>required sint32 node_id = 10;</code>
     */
    public boolean hasNodeId() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>required sint32 node_id = 10;</code>
     */
    public int getNodeId() {
      return nodeId_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasModuleId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLogType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLogLevel()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLogMessage()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasErrorCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTimeStamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDefaultFormattedMessage()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNodeId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getUserValuesCount(); i++) {
        if (!getUserValues(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeSInt32(1, moduleId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeSInt32(2, logType_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeSInt32(3, logLevel_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, logMessage_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, exception_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeSInt64(6, errorCode_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeSInt64(7, timeStamp_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, defaultFormattedMessage_);
      }
      for (int i = 0; i < userValues_.size(); i++) {
        output.writeMessage(9, userValues_.get(i));
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeSInt32(10, nodeId_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(1, moduleId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(2, logType_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(3, logLevel_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, logMessage_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, exception_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt64Size(6, errorCode_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt64Size(7, timeStamp_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, defaultFormattedMessage_);
      }
      for (int i = 0; i < userValues_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(9, userValues_.get(i));
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(10, nodeId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.bdtd.card.common.log.protobuf.PBLog.PBLogInfo)) {
        return super.equals(obj);
      }
      com.bdtd.card.common.log.protobuf.PBLog.PBLogInfo other = (com.bdtd.card.common.log.protobuf.PBLog.PBLogInfo) obj;

      boolean result = true;
      result = result && (hasModuleId() == other.hasModuleId());
      if (hasModuleId()) {
        result = result && (getModuleId()
            == other.getModuleId());
      }
      result = result && (hasLogType() == other.hasLogType());
      if (hasLogType()) {
        result = result && (getLogType()
            == other.getLogType());
      }
      result = result && (hasLogLevel() == other.hasLogLevel());
      if (hasLogLevel()) {
        result = result && (getLogLevel()
            == other.getLogLevel());
      }
      result = result && (hasLogMessage() == other.hasLogMessage());
      if (hasLogMessage()) {
        result = result && getLogMessage()
            .equals(other.getLogMessage());
      }
      result = result && (hasException() == other.hasException());
      if (hasException()) {
        result = result && getException()
            .equals(other.getException());
      }
      result = result && (hasErrorCode() == other.hasErrorCode());
      if (hasErrorCode()) {
        result = result && (getErrorCode()
            == other.getErrorCode());
      }
      result = result && (hasTimeStamp() == other.hasTimeStamp());
      if (hasTimeStamp()) {
        result = result && (getTimeStamp()
            == other.getTimeStamp());
      }
      result = result && (hasDefaultFormattedMessage() == other.hasDefaultFormattedMessage());
      if (hasDefaultFormattedMessage()) {
        result = result && getDefaultFormattedMessage()
            .equals(other.getDefaultFormattedMessage());
      }
      result = result && getUserValuesList()
          .equals(other.getUserValuesList());
      result = result && (hasNodeId() == other.hasNodeId());
      if (hasNodeId()) {
        result = result && (getNodeId()
            == other.getNodeId());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasModuleId()) {
        hash = (37 * hash) + MODULE_ID_FIELD_NUMBER;
        hash = (53 * hash) + getModuleId();
      }
      if (hasLogType()) {
        hash = (37 * hash) + LOG_TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getLogType();
      }
      if (hasLogLevel()) {
        hash = (37 * hash) + LOG_LEVEL_FIELD_NUMBER;
        hash = (53 * hash) + getLogLevel();
      }
      if (hasLogMessage()) {
        hash = (37 * hash) + LOG_MESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getLogMessage().hashCode();
      }
      if (hasException()) {
        hash = (37 * hash) + EXCEPTION_FIELD_NUMBER;
        hash = (53 * hash) + getException().hashCode();
      }
      if (hasErrorCode()) {
        hash = (37 * hash) + ERROR_CODE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getErrorCode());
      }
      if (hasTimeStamp()) {
        hash = (37 * hash) + TIME_STAMP_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getTimeStamp());
      }
      if (hasDefaultFormattedMessage()) {
        hash = (37 * hash) + DEFAULT_FORMATTED_MESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getDefaultFormattedMessage().hashCode();
      }
      if (getUserValuesCount() > 0) {
        hash = (37 * hash) + USER_VALUES_FIELD_NUMBER;
        hash = (53 * hash) + getUserValuesList().hashCode();
      }
      if (hasNodeId()) {
        hash = (37 * hash) + NODE_ID_FIELD_NUMBER;
        hash = (53 * hash) + getNodeId();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.bdtd.card.common.log.protobuf.PBLog.PBLogInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bdtd.card.common.log.protobuf.PBLog.PBLogInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bdtd.card.common.log.protobuf.PBLog.PBLogInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bdtd.card.common.log.protobuf.PBLog.PBLogInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bdtd.card.common.log.protobuf.PBLog.PBLogInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bdtd.card.common.log.protobuf.PBLog.PBLogInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bdtd.card.common.log.protobuf.PBLog.PBLogInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.bdtd.card.common.log.protobuf.PBLog.PBLogInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bdtd.card.common.log.protobuf.PBLog.PBLogInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bdtd.card.common.log.protobuf.PBLog.PBLogInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.bdtd.card.common.log.protobuf.PBLog.PBLogInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code VWVO.NetworkComponent.Globals.Command.Protobuf.PBLogInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:VWVO.NetworkComponent.Globals.Command.Protobuf.PBLogInfo)
        com.bdtd.card.common.log.protobuf.PBLog.PBLogInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.bdtd.card.common.log.protobuf.PBLog.internal_static_VWVO_NetworkComponent_Globals_Command_Protobuf_PBLogInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.bdtd.card.common.log.protobuf.PBLog.internal_static_VWVO_NetworkComponent_Globals_Command_Protobuf_PBLogInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.bdtd.card.common.log.protobuf.PBLog.PBLogInfo.class, com.bdtd.card.common.log.protobuf.PBLog.PBLogInfo.Builder.class);
      }

      // Construct using com.bdtd.card.base.common.log.protobuf.PBLog.PBLogInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getUserValuesFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        moduleId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        logType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        logLevel_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        logMessage_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        exception_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        errorCode_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000020);
        timeStamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000040);
        defaultFormattedMessage_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        if (userValuesBuilder_ == null) {
          userValues_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000100);
        } else {
          userValuesBuilder_.clear();
        }
        nodeId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000200);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bdtd.card.common.log.protobuf.PBLog.internal_static_VWVO_NetworkComponent_Globals_Command_Protobuf_PBLogInfo_descriptor;
      }

      public com.bdtd.card.common.log.protobuf.PBLog.PBLogInfo getDefaultInstanceForType() {
        return com.bdtd.card.common.log.protobuf.PBLog.PBLogInfo.getDefaultInstance();
      }

      public com.bdtd.card.common.log.protobuf.PBLog.PBLogInfo build() {
        com.bdtd.card.common.log.protobuf.PBLog.PBLogInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.bdtd.card.common.log.protobuf.PBLog.PBLogInfo buildPartial() {
        com.bdtd.card.common.log.protobuf.PBLog.PBLogInfo result = new com.bdtd.card.common.log.protobuf.PBLog.PBLogInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.moduleId_ = moduleId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.logType_ = logType_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.logLevel_ = logLevel_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.logMessage_ = logMessage_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.exception_ = exception_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.errorCode_ = errorCode_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.timeStamp_ = timeStamp_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.defaultFormattedMessage_ = defaultFormattedMessage_;
        if (userValuesBuilder_ == null) {
          if (((bitField0_ & 0x00000100) == 0x00000100)) {
            userValues_ = java.util.Collections.unmodifiableList(userValues_);
            bitField0_ = (bitField0_ & ~0x00000100);
          }
          result.userValues_ = userValues_;
        } else {
          result.userValues_ = userValuesBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000100;
        }
        result.nodeId_ = nodeId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bdtd.card.common.log.protobuf.PBLog.PBLogInfo) {
          return mergeFrom((com.bdtd.card.common.log.protobuf.PBLog.PBLogInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.bdtd.card.common.log.protobuf.PBLog.PBLogInfo other) {
        if (other == com.bdtd.card.common.log.protobuf.PBLog.PBLogInfo.getDefaultInstance()) return this;
        if (other.hasModuleId()) {
          setModuleId(other.getModuleId());
        }
        if (other.hasLogType()) {
          setLogType(other.getLogType());
        }
        if (other.hasLogLevel()) {
          setLogLevel(other.getLogLevel());
        }
        if (other.hasLogMessage()) {
          bitField0_ |= 0x00000008;
          logMessage_ = other.logMessage_;
          onChanged();
        }
        if (other.hasException()) {
          bitField0_ |= 0x00000010;
          exception_ = other.exception_;
          onChanged();
        }
        if (other.hasErrorCode()) {
          setErrorCode(other.getErrorCode());
        }
        if (other.hasTimeStamp()) {
          setTimeStamp(other.getTimeStamp());
        }
        if (other.hasDefaultFormattedMessage()) {
          bitField0_ |= 0x00000080;
          defaultFormattedMessage_ = other.defaultFormattedMessage_;
          onChanged();
        }
        if (userValuesBuilder_ == null) {
          if (!other.userValues_.isEmpty()) {
            if (userValues_.isEmpty()) {
              userValues_ = other.userValues_;
              bitField0_ = (bitField0_ & ~0x00000100);
            } else {
              ensureUserValuesIsMutable();
              userValues_.addAll(other.userValues_);
            }
            onChanged();
          }
        } else {
          if (!other.userValues_.isEmpty()) {
            if (userValuesBuilder_.isEmpty()) {
              userValuesBuilder_.dispose();
              userValuesBuilder_ = null;
              userValues_ = other.userValues_;
              bitField0_ = (bitField0_ & ~0x00000100);
              userValuesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getUserValuesFieldBuilder() : null;
            } else {
              userValuesBuilder_.addAllMessages(other.userValues_);
            }
          }
        }
        if (other.hasNodeId()) {
          setNodeId(other.getNodeId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasModuleId()) {
          return false;
        }
        if (!hasLogType()) {
          return false;
        }
        if (!hasLogLevel()) {
          return false;
        }
        if (!hasLogMessage()) {
          return false;
        }
        if (!hasErrorCode()) {
          return false;
        }
        if (!hasTimeStamp()) {
          return false;
        }
        if (!hasDefaultFormattedMessage()) {
          return false;
        }
        if (!hasNodeId()) {
          return false;
        }
        for (int i = 0; i < getUserValuesCount(); i++) {
          if (!getUserValues(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.bdtd.card.common.log.protobuf.PBLog.PBLogInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.bdtd.card.common.log.protobuf.PBLog.PBLogInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int moduleId_ ;
      /**
       * <code>required sint32 module_id = 1;</code>
       */
      public boolean hasModuleId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required sint32 module_id = 1;</code>
       */
      public int getModuleId() {
        return moduleId_;
      }
      /**
       * <code>required sint32 module_id = 1;</code>
       */
      public Builder setModuleId(int value) {
        bitField0_ |= 0x00000001;
        moduleId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required sint32 module_id = 1;</code>
       */
      public Builder clearModuleId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        moduleId_ = 0;
        onChanged();
        return this;
      }

      private int logType_ ;
      /**
       * <code>required sint32 log_type = 2;</code>
       */
      public boolean hasLogType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required sint32 log_type = 2;</code>
       */
      public int getLogType() {
        return logType_;
      }
      /**
       * <code>required sint32 log_type = 2;</code>
       */
      public Builder setLogType(int value) {
        bitField0_ |= 0x00000002;
        logType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required sint32 log_type = 2;</code>
       */
      public Builder clearLogType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        logType_ = 0;
        onChanged();
        return this;
      }

      private int logLevel_ ;
      /**
       * <code>required sint32 log_level = 3;</code>
       */
      public boolean hasLogLevel() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required sint32 log_level = 3;</code>
       */
      public int getLogLevel() {
        return logLevel_;
      }
      /**
       * <code>required sint32 log_level = 3;</code>
       */
      public Builder setLogLevel(int value) {
        bitField0_ |= 0x00000004;
        logLevel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required sint32 log_level = 3;</code>
       */
      public Builder clearLogLevel() {
        bitField0_ = (bitField0_ & ~0x00000004);
        logLevel_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object logMessage_ = "";
      /**
       * <code>required string log_message = 4;</code>
       */
      public boolean hasLogMessage() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string log_message = 4;</code>
       */
      public java.lang.String getLogMessage() {
        java.lang.Object ref = logMessage_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            logMessage_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string log_message = 4;</code>
       */
      public com.google.protobuf.ByteString
          getLogMessageBytes() {
        java.lang.Object ref = logMessage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          logMessage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string log_message = 4;</code>
       */
      public Builder setLogMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        logMessage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string log_message = 4;</code>
       */
      public Builder clearLogMessage() {
        bitField0_ = (bitField0_ & ~0x00000008);
        logMessage_ = getDefaultInstance().getLogMessage();
        onChanged();
        return this;
      }
      /**
       * <code>required string log_message = 4;</code>
       */
      public Builder setLogMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        logMessage_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object exception_ = "";
      /**
       * <code>optional string exception = 5;</code>
       */
      public boolean hasException() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string exception = 5;</code>
       */
      public java.lang.String getException() {
        java.lang.Object ref = exception_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            exception_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string exception = 5;</code>
       */
      public com.google.protobuf.ByteString
          getExceptionBytes() {
        java.lang.Object ref = exception_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          exception_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string exception = 5;</code>
       */
      public Builder setException(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        exception_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string exception = 5;</code>
       */
      public Builder clearException() {
        bitField0_ = (bitField0_ & ~0x00000010);
        exception_ = getDefaultInstance().getException();
        onChanged();
        return this;
      }
      /**
       * <code>optional string exception = 5;</code>
       */
      public Builder setExceptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        exception_ = value;
        onChanged();
        return this;
      }

      private long errorCode_ ;
      /**
       * <code>required sint64 error_code = 6;</code>
       */
      public boolean hasErrorCode() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required sint64 error_code = 6;</code>
       */
      public long getErrorCode() {
        return errorCode_;
      }
      /**
       * <code>required sint64 error_code = 6;</code>
       */
      public Builder setErrorCode(long value) {
        bitField0_ |= 0x00000020;
        errorCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required sint64 error_code = 6;</code>
       */
      public Builder clearErrorCode() {
        bitField0_ = (bitField0_ & ~0x00000020);
        errorCode_ = 0L;
        onChanged();
        return this;
      }

      private long timeStamp_ ;
      /**
       * <code>required sint64 time_stamp = 7;</code>
       */
      public boolean hasTimeStamp() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required sint64 time_stamp = 7;</code>
       */
      public long getTimeStamp() {
        return timeStamp_;
      }
      /**
       * <code>required sint64 time_stamp = 7;</code>
       */
      public Builder setTimeStamp(long value) {
        bitField0_ |= 0x00000040;
        timeStamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required sint64 time_stamp = 7;</code>
       */
      public Builder clearTimeStamp() {
        bitField0_ = (bitField0_ & ~0x00000040);
        timeStamp_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object defaultFormattedMessage_ = "";
      /**
       * <code>required string default_formatted_message = 8;</code>
       */
      public boolean hasDefaultFormattedMessage() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>required string default_formatted_message = 8;</code>
       */
      public java.lang.String getDefaultFormattedMessage() {
        java.lang.Object ref = defaultFormattedMessage_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            defaultFormattedMessage_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string default_formatted_message = 8;</code>
       */
      public com.google.protobuf.ByteString
          getDefaultFormattedMessageBytes() {
        java.lang.Object ref = defaultFormattedMessage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          defaultFormattedMessage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string default_formatted_message = 8;</code>
       */
      public Builder setDefaultFormattedMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        defaultFormattedMessage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string default_formatted_message = 8;</code>
       */
      public Builder clearDefaultFormattedMessage() {
        bitField0_ = (bitField0_ & ~0x00000080);
        defaultFormattedMessage_ = getDefaultInstance().getDefaultFormattedMessage();
        onChanged();
        return this;
      }
      /**
       * <code>required string default_formatted_message = 8;</code>
       */
      public Builder setDefaultFormattedMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        defaultFormattedMessage_ = value;
        onChanged();
        return this;
      }

      private java.util.List<com.bdtd.card.common.log.protobuf.PBLog.PBKeyValuePair> userValues_ =
        java.util.Collections.emptyList();
      private void ensureUserValuesIsMutable() {
        if (!((bitField0_ & 0x00000100) == 0x00000100)) {
          userValues_ = new java.util.ArrayList<com.bdtd.card.common.log.protobuf.PBLog.PBKeyValuePair>(userValues_);
          bitField0_ |= 0x00000100;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.bdtd.card.common.log.protobuf.PBLog.PBKeyValuePair, com.bdtd.card.common.log.protobuf.PBLog.PBKeyValuePair.Builder, com.bdtd.card.common.log.protobuf.PBLog.PBKeyValuePairOrBuilder> userValuesBuilder_;

      /**
       * <code>repeated .VWVO.NetworkComponent.Globals.Command.Protobuf.PBKeyValuePair user_values = 9;</code>
       */
      public java.util.List<com.bdtd.card.common.log.protobuf.PBLog.PBKeyValuePair> getUserValuesList() {
        if (userValuesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(userValues_);
        } else {
          return userValuesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .VWVO.NetworkComponent.Globals.Command.Protobuf.PBKeyValuePair user_values = 9;</code>
       */
      public int getUserValuesCount() {
        if (userValuesBuilder_ == null) {
          return userValues_.size();
        } else {
          return userValuesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .VWVO.NetworkComponent.Globals.Command.Protobuf.PBKeyValuePair user_values = 9;</code>
       */
      public com.bdtd.card.common.log.protobuf.PBLog.PBKeyValuePair getUserValues(int index) {
        if (userValuesBuilder_ == null) {
          return userValues_.get(index);
        } else {
          return userValuesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .VWVO.NetworkComponent.Globals.Command.Protobuf.PBKeyValuePair user_values = 9;</code>
       */
      public Builder setUserValues(
          int index, com.bdtd.card.common.log.protobuf.PBLog.PBKeyValuePair value) {
        if (userValuesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUserValuesIsMutable();
          userValues_.set(index, value);
          onChanged();
        } else {
          userValuesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .VWVO.NetworkComponent.Globals.Command.Protobuf.PBKeyValuePair user_values = 9;</code>
       */
      public Builder setUserValues(
          int index, com.bdtd.card.common.log.protobuf.PBLog.PBKeyValuePair.Builder builderForValue) {
        if (userValuesBuilder_ == null) {
          ensureUserValuesIsMutable();
          userValues_.set(index, builderForValue.build());
          onChanged();
        } else {
          userValuesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .VWVO.NetworkComponent.Globals.Command.Protobuf.PBKeyValuePair user_values = 9;</code>
       */
      public Builder addUserValues(com.bdtd.card.common.log.protobuf.PBLog.PBKeyValuePair value) {
        if (userValuesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUserValuesIsMutable();
          userValues_.add(value);
          onChanged();
        } else {
          userValuesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .VWVO.NetworkComponent.Globals.Command.Protobuf.PBKeyValuePair user_values = 9;</code>
       */
      public Builder addUserValues(
          int index, com.bdtd.card.common.log.protobuf.PBLog.PBKeyValuePair value) {
        if (userValuesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUserValuesIsMutable();
          userValues_.add(index, value);
          onChanged();
        } else {
          userValuesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .VWVO.NetworkComponent.Globals.Command.Protobuf.PBKeyValuePair user_values = 9;</code>
       */
      public Builder addUserValues(
          com.bdtd.card.common.log.protobuf.PBLog.PBKeyValuePair.Builder builderForValue) {
        if (userValuesBuilder_ == null) {
          ensureUserValuesIsMutable();
          userValues_.add(builderForValue.build());
          onChanged();
        } else {
          userValuesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .VWVO.NetworkComponent.Globals.Command.Protobuf.PBKeyValuePair user_values = 9;</code>
       */
      public Builder addUserValues(
          int index, com.bdtd.card.common.log.protobuf.PBLog.PBKeyValuePair.Builder builderForValue) {
        if (userValuesBuilder_ == null) {
          ensureUserValuesIsMutable();
          userValues_.add(index, builderForValue.build());
          onChanged();
        } else {
          userValuesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .VWVO.NetworkComponent.Globals.Command.Protobuf.PBKeyValuePair user_values = 9;</code>
       */
      public Builder addAllUserValues(
          java.lang.Iterable<? extends com.bdtd.card.common.log.protobuf.PBLog.PBKeyValuePair> values) {
        if (userValuesBuilder_ == null) {
          ensureUserValuesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, userValues_);
          onChanged();
        } else {
          userValuesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .VWVO.NetworkComponent.Globals.Command.Protobuf.PBKeyValuePair user_values = 9;</code>
       */
      public Builder clearUserValues() {
        if (userValuesBuilder_ == null) {
          userValues_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000100);
          onChanged();
        } else {
          userValuesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .VWVO.NetworkComponent.Globals.Command.Protobuf.PBKeyValuePair user_values = 9;</code>
       */
      public Builder removeUserValues(int index) {
        if (userValuesBuilder_ == null) {
          ensureUserValuesIsMutable();
          userValues_.remove(index);
          onChanged();
        } else {
          userValuesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .VWVO.NetworkComponent.Globals.Command.Protobuf.PBKeyValuePair user_values = 9;</code>
       */
      public com.bdtd.card.common.log.protobuf.PBLog.PBKeyValuePair.Builder getUserValuesBuilder(
          int index) {
        return getUserValuesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .VWVO.NetworkComponent.Globals.Command.Protobuf.PBKeyValuePair user_values = 9;</code>
       */
      public com.bdtd.card.common.log.protobuf.PBLog.PBKeyValuePairOrBuilder getUserValuesOrBuilder(
          int index) {
        if (userValuesBuilder_ == null) {
          return userValues_.get(index);  } else {
          return userValuesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .VWVO.NetworkComponent.Globals.Command.Protobuf.PBKeyValuePair user_values = 9;</code>
       */
      public java.util.List<? extends com.bdtd.card.common.log.protobuf.PBLog.PBKeyValuePairOrBuilder> 
           getUserValuesOrBuilderList() {
        if (userValuesBuilder_ != null) {
          return userValuesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(userValues_);
        }
      }
      /**
       * <code>repeated .VWVO.NetworkComponent.Globals.Command.Protobuf.PBKeyValuePair user_values = 9;</code>
       */
      public com.bdtd.card.common.log.protobuf.PBLog.PBKeyValuePair.Builder addUserValuesBuilder() {
        return getUserValuesFieldBuilder().addBuilder(
            com.bdtd.card.common.log.protobuf.PBLog.PBKeyValuePair.getDefaultInstance());
      }
      /**
       * <code>repeated .VWVO.NetworkComponent.Globals.Command.Protobuf.PBKeyValuePair user_values = 9;</code>
       */
      public com.bdtd.card.common.log.protobuf.PBLog.PBKeyValuePair.Builder addUserValuesBuilder(
          int index) {
        return getUserValuesFieldBuilder().addBuilder(
            index, com.bdtd.card.common.log.protobuf.PBLog.PBKeyValuePair.getDefaultInstance());
      }
      /**
       * <code>repeated .VWVO.NetworkComponent.Globals.Command.Protobuf.PBKeyValuePair user_values = 9;</code>
       */
      public java.util.List<com.bdtd.card.common.log.protobuf.PBLog.PBKeyValuePair.Builder> 
           getUserValuesBuilderList() {
        return getUserValuesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.bdtd.card.common.log.protobuf.PBLog.PBKeyValuePair, com.bdtd.card.common.log.protobuf.PBLog.PBKeyValuePair.Builder, com.bdtd.card.common.log.protobuf.PBLog.PBKeyValuePairOrBuilder> 
          getUserValuesFieldBuilder() {
        if (userValuesBuilder_ == null) {
          userValuesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.bdtd.card.common.log.protobuf.PBLog.PBKeyValuePair, com.bdtd.card.common.log.protobuf.PBLog.PBKeyValuePair.Builder, com.bdtd.card.common.log.protobuf.PBLog.PBKeyValuePairOrBuilder>(
                  userValues_,
                  ((bitField0_ & 0x00000100) == 0x00000100),
                  getParentForChildren(),
                  isClean());
          userValues_ = null;
        }
        return userValuesBuilder_;
      }

      private int nodeId_ ;
      /**
       * <code>required sint32 node_id = 10;</code>
       */
      public boolean hasNodeId() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>required sint32 node_id = 10;</code>
       */
      public int getNodeId() {
        return nodeId_;
      }
      /**
       * <code>required sint32 node_id = 10;</code>
       */
      public Builder setNodeId(int value) {
        bitField0_ |= 0x00000200;
        nodeId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required sint32 node_id = 10;</code>
       */
      public Builder clearNodeId() {
        bitField0_ = (bitField0_ & ~0x00000200);
        nodeId_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:VWVO.NetworkComponent.Globals.Command.Protobuf.PBLogInfo)
    }

    // @@protoc_insertion_point(class_scope:VWVO.NetworkComponent.Globals.Command.Protobuf.PBLogInfo)
    private static final com.bdtd.card.common.log.protobuf.PBLog.PBLogInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.bdtd.card.common.log.protobuf.PBLog.PBLogInfo();
    }

    public static com.bdtd.card.common.log.protobuf.PBLog.PBLogInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<PBLogInfo>
        PARSER = new com.google.protobuf.AbstractParser<PBLogInfo>() {
      public PBLogInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PBLogInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PBLogInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PBLogInfo> getParserForType() {
      return PARSER;
    }

    public com.bdtd.card.common.log.protobuf.PBLog.PBLogInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_VWVO_NetworkComponent_Globals_Command_Protobuf_PBKeyValuePair_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_VWVO_NetworkComponent_Globals_Command_Protobuf_PBKeyValuePair_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_VWVO_NetworkComponent_Globals_Command_Protobuf_PBLogInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_VWVO_NetworkComponent_Globals_Command_Protobuf_PBLogInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013PBLog.proto\022.VWVO.NetworkComponent.Glo" +
      "bals.Command.Protobuf\",\n\016PBKeyValuePair\022" +
      "\013\n\003key\030\001 \002(\t\022\r\n\005value\030\002 \002(\t\"\234\002\n\tPBLogInf" +
      "o\022\021\n\tmodule_id\030\001 \002(\021\022\020\n\010log_type\030\002 \002(\021\022\021" +
      "\n\tlog_level\030\003 \002(\021\022\023\n\013log_message\030\004 \002(\t\022\021" +
      "\n\texception\030\005 \001(\t\022\022\n\nerror_code\030\006 \002(\022\022\022\n" +
      "\ntime_stamp\030\007 \002(\022\022!\n\031default_formatted_m" +
      "essage\030\010 \002(\t\022S\n\013user_values\030\t \003(\0132>.VWVO" +
      ".NetworkComponent.Globals.Command.Protob" +
      "uf.PBKeyValuePair\022\017\n\007node_id\030\n \002(\021B%\n\034ne",
      "t.vwvo.common.log.protobufB\005PBLog"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_VWVO_NetworkComponent_Globals_Command_Protobuf_PBKeyValuePair_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_VWVO_NetworkComponent_Globals_Command_Protobuf_PBKeyValuePair_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_VWVO_NetworkComponent_Globals_Command_Protobuf_PBKeyValuePair_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_VWVO_NetworkComponent_Globals_Command_Protobuf_PBLogInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_VWVO_NetworkComponent_Globals_Command_Protobuf_PBLogInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_VWVO_NetworkComponent_Globals_Command_Protobuf_PBLogInfo_descriptor,
        new java.lang.String[] { "ModuleId", "LogType", "LogLevel", "LogMessage", "Exception", "ErrorCode", "TimeStamp", "DefaultFormattedMessage", "UserValues", "NodeId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
